using System;
using System.Collections.Generic;
using System.Text;

namespace CSharp
{
    // a class can be splited in 2 classes with the same name
    // separate autogenerated code from the developer code
    class ClassesPartial
    {
        public ClassesPartial()
        {

        }
    }

    // - all classes must have the same name and partial keyword (partial class ClassName)
    // - the same access modifier (public, internal)
    // - if one is abstract(can not be instantiated) all will be abstract even if they do not have the abstract keyword
    //        (public abstract partial class ClassName{} )
    // - if one is sealed (can not act as BaseClass(can not have children)), entire type will become sealed 
    //        (public sealed partial class ClassName)
    // - if any part inherit a class, the entire type will inherit that class
    public partial class PartialCustomer
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
    public partial class PartialCustomer
    {
        public string GetFullName()
        {
            return FirstName + LastName;
        }
    }
}
